### PR TITLE
Fix Throw Error if Const Declaration isn't Initialized

### PR DESCRIPTION
**Pull request by glasss13**
It is a Syntax Error if Initializer is not present and IsConstantDeclaration of the LexicalDeclaration containing this LexicalBinding is true.

### CODE REVIEW

**Comment by mattco98** [comment]
This is not where this check should be performed. Throwing an IllegalStateException would crash the whole program. Instead, the check should be done at the appropriate place in the Parser, and the error should be generated via one of the error reporting functions, like `reportError`.

**Comment by glasss13** [comment]
> This is not where this check should be performed. Throwing an IllegalStateException would crash the whole program. Instead, the check should be done at the appropriate place in the Parser, and the error should be generated via one of the error reporting functions, like `reportError`.

Ah yea that was pretty stupid of me to only test Rhino and not actually with CT. I'll go look around through the code for that. It's pretty cool to see all of it behind the scenes.

**Comment by glasss13** [comment]
What is the proper way to add an error message? I tried adding it to the main Messages.properties resource but it couldn't find it and I'm pretty sure it says that's not the place to do it. I tried making a Message_en_us.properties but it still couldn't find it and also that seems like a bad solution because someone not in that locale wouldn't get it. I feel like I'm probably misunderstanding so any help is appreciated.

**Comment by glasss13** [comment]
lol noob

**Pull request closed without merging**
